version: '3.7'
services:
  k4frontend:
    build:
      context: .
      args:
        VUE_APP_API_BASE_URL: "http://0.0.0.0:8080/api/v1/"
        VUE_APP_TITLE: "k4frontend"
    ports:
      - "3000:80"
      - "3001:443"
